
package dormidos_pizza;

import javax.swing.WindowConstants;


public class Administracion extends javax.swing.JFrame {
    
    String admin;

    public Administracion() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        
        //evitar que el programa termine al cerrar la ventana
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_sucursal = new javax.swing.JLabel();
        jComboBox_sucursal = new javax.swing.JComboBox<>();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_pizzaname = new javax.swing.JLabel();
        jLabel_descripcion = new javax.swing.JLabel();
        jTextField_pizzaname = new javax.swing.JTextField();
        jTextField_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_tabla = new javax.swing.JTable();
        jButton_crear = new javax.swing.JButton();
        jLabel_fondoadmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_sucursal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel_sucursal.setText("SUCURSAL");
        getContentPane().add(jLabel_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 30));

        jComboBox_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 230, 30));

        jLabel_precio.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel_precio.setText("PRECIO");
        getContentPane().add(jLabel_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, 30));

        jLabel_pizzaname.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel_pizzaname.setText("PIZZA");
        getContentPane().add(jLabel_pizzaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        jLabel_descripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel_descripcion.setText("DESCRIPCION");
        getContentPane().add(jLabel_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 30));
        getContentPane().add(jTextField_pizzaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, 40));
        getContentPane().add(jTextField_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 100, 40));

        jTextArea_descripcion.setColumns(20);
        jTextArea_descripcion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, 90));

        jTable_tabla.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jTable_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "DESCRIPCION", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(jTable_tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 470, 140));

        jButton_crear.setBackground(new java.awt.Color(255, 153, 102));
        jButton_crear.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jButton_crear.setText("CREAR");
        getContentPane().add(jButton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, 40));
        getContentPane().add(jLabel_fondoadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_crear;
    private javax.swing.JComboBox<String> jComboBox_sucursal;
    private javax.swing.JLabel jLabel_descripcion;
    private javax.swing.JLabel jLabel_fondoadmin;
    private javax.swing.JLabel jLabel_pizzaname;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JLabel jLabel_sucursal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_tabla;
    private javax.swing.JTextArea jTextArea_descripcion;
    private javax.swing.JTextField jTextField_pizzaname;
    private javax.swing.JTextField jTextField_precio;
    // End of variables declaration//GEN-END:variables
}
